spring:
  main:
    banner-mode: off

resilience4j:
  retry:
    instances:
      atmRetry:
        max-attempts: 3
        wait-duration: 2s
  circuitbreaker:
    instances:
      atmCircuitBreaker:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
