server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/cuenta/**
        - id: transaction-service
          uri: http://localhost:8083
          predicates:
            - Path=/transaccion/**
